---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - my-custom-app.stickers.com
  resources:
  - mypythonapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - my-custom-app.stickers.com
  resources:
  - mypythonapps/finalizers
  verbs:
  - update
- apiGroups:
  - my-custom-app.stickers.com
  resources:
  - mypythonapps/status
  verbs:
  - get
  - patch
  - update
